## Investigating the `TotalCharges` Feature

The `TotalCharges` feature should contain numerical values. However, it is currently stored as a string, indicating that some values may not be valid numbers.

Before converting its data type, we need to identify the records causing this issue.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Optional configuration for visual improvement

plt.style.use("default")
pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [4]:
# Display the current data type

display(df["TotalCharges"].dtype)

In [5]:
# Identify non-numeric values

invalid_total_charges = df[pd.to_numeric(df["TotalCharges"], errors="coerce").isna()]

display(invalid_total_charges)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

## Converting `TotalCharges` to Numeric

The `TotalCharges` feature is currently stored as a string due to the presence of empty values.

The feature will be converted to a numerical data type, replacing invalid values with `NaN` for further processing.

In [6]:
# Convert TotalCharges to numeric

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

display(df["TotalCharges"].dtype)

dtype('float64')

## Missing Values After Data Type Conversion

After converting the `TotalCharges` feature, invalid entries become missing values (`NaN`), allowing them to be properly identified and handled.

In [7]:
# Count missing values

display(df.isnull().sum())

# Calculate missing value percentages

missing_values = (
    df.isnull()
      .sum()
      .to_frame(name="Missing Values")
)

missing_values["Percentage"] = (
    missing_values["Missing Values"] / len(df) * 100
).round(2)

display(missing_values)

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

                  Missing Values  Percentage
customerID                     0        0.00
gender                         0        0.00
SeniorCitizen                  0        0.00
Partner                        0        0.00
Dependents                     0        0.00
tenure                         0        0.00
PhoneService                   0        0.00
MultipleLines                  0        0.00
InternetService                0        0.00
OnlineSecurity                 0        0.00
OnlineBackup                   0        0.00
DeviceProtection               0        0.00
TechSupport                    0        0.00
StreamingTV                    0        0.00
StreamingMovies                0        0.00
Contract                       0        0.00
PaperlessBilling               0        0.00
PaymentMethod                  0        0.00
MonthlyCharges                 0        0.00
TotalCharges                  11        0.16
Churn                          0        0.00

## Handling Missing Values

The `TotalCharges` feature contains 11 missing values that appeared after converting the column to a numerical data type.

These records correspond to customers with a tenure of zero months, indicating that they are new customers who have not yet accumulated any charges.

Since the missing values represent only a very small portion of the dataset, removing these records is considered an appropriate approach.

In [8]:
# Remove rows with missing values

df = df.dropna()

display(df.isnull().sum())

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

## Duplicate Records Validation

After handling missing values, the dataset is inspected again to ensure that no duplicate records are present.

In [9]:
# Verify duplicate records

display(df.duplicated().sum())

np.int64(0)

## Numerical Feature Validation

Numerical variables are inspected to identify potential inconsistencies such as unexpected minimum values or unrealistic ranges.

In [10]:
# Generate descriptive statistics

display(df.describe())

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7032.000000  7032.000000     7032.000000   7032.000000
mean        0.162400    32.421786       64.798208   2283.300441
std         0.368844    24.545260       30.085974   2266.771362
min         0.000000     1.000000       18.250000     18.800000
25%         0.000000     9.000000       35.587500    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.862500   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

## Categorical Feature Validation

Each categorical feature is inspected to verify that its values are consistent and do not contain unexpected categories.

In [11]:
# Display unique values for categorical features

for column in df.select_dtypes(include=["object", "string"]).columns:
    print(f"\n{column}")
    print(df[column].unique())

customerID
<StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7032, dtype: str

gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str

Partner
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

Dependents
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

PhoneService
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

MultipleLines
<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

InternetService
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

OnlineSecurity
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

OnlineBackup
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

DeviceProtection
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

TechSupport
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

StreamingTV
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

StreamingMovies
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Contract
<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

PaperlessBilling
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

PaymentMethod
<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

Churn
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

## Final Dataset Validation

The dataset is validated after the cleaning process to ensure that all variables have the correct data types and that no missing values remain.

In [13]:
# Display dataset information

display(df.info())

# Display dataset shape

display(df.shape)

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.2 MB

None

(7032, 21)

## Saving the Clean Dataset

The cleaned dataset is stored in the `processed` directory and will be used during the exploratory data analysis and machine learning phases.

In [14]:
# Save cleaned dataset

df.to_csv("../data/processed/customer_churn_clean.csv", index=False)

## Final Observations

- The `TotalCharges` feature was successfully converted to a numerical data type.
- Eleven missing values were identified after the conversion and removed from the dataset.
- No duplicate records were found.
- Numerical features present valid ranges.
- Categorical variables contain consistent values.
- The cleaned dataset is ready for exploratory data analysis.